name: Build, Test, and Verify

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'maven'
      - name: Maven Verify (build and test)
        run: mvn --batch-mode --no-transfer-progress verify
